name: Publish Dev Container templates
description: 🚀 Publish your Dev Container templates monorepo

branding:
  icon: upload-cloud
  color: blue

inputs:
  path:
    default: src
  collection:
    default: ghcr.io/${{ github.repository }}
  update-tags:
    default: true

runs:
  using: composite
  steps:
    - shell: bash
      run: npm install -g @devcontainers/cli
    - id: main
      run: '"$GITHUB_ACTION_PATH/main.sh"'
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
        INPUT_COLLECTION: ${{ inputs.collection }}
        INPUT_UPDATE_TAGS: ${{ inputs.update-tags }}
